version: 2
jobs:
  run_unit_tests:
    docker:
      - image: circleci/golang:1.12.5
        environment:
          GO111MODULE: "on"

    working_directory: /go/src/github.com/xridge/kubestone
    steps:
      - checkout
      - run:
          name: Install kubebuilder
          command: |
            version=2.0.0-beta.0
            arch=amd64
            curl -L -O https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${version}/kubebuilder_${version}_linux_${arch}.tar.gz
            tar -zxvf kubebuilder_${version}_linux_${arch}.tar.gz
            sudo mv kubebuilder_${version}_linux_${arch} /usr/local/kubebuilder
            export PATH=$PATH:/usr/local/kubebuilder/bin
      - run: make test

  run_e2e_tests:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

    working_directory: ~/go/src/github.com/xridge/kubestone
    steps:
      - checkout
      - run:
          name: Upgrade golang to 1.12
          command: |
            sudo apt-get -y remove golang
            ls -l /usr/local
            VERSION=1.12.8
            OS=linux
            ARCH=amd64
            cd /tmp
            curl -L -O https://dl.google.com/go/go${VERSION}.${OS}-${ARCH}.tar.gz
            sudo tar -C /usr/local -xzf go$VERSION.$OS-$ARCH.tar.gz
            echo "export PATH=$PATH:/usr/local/go/bin" >> ~/.profile
      - run:
          name: Start e2e test
          command: |
            ./tests/e2e/e2e-test-in-kind.sh

workflows:
  version: 2
  test:
    jobs:
      - run_unit_tests
      - run_e2e_tests