# permissions to do edit ycsbbenches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ycsbbench-editor-role
rules:
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - ycsbbenches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - ycsbbenches/status
  verbs:
  - get
  - patch
  - update
