apiVersion: perf.kubestone.xridge.io/v1alpha1
kind: EsRally
metadata:
  name: esrally-sample
spec:
  track: eventdata
  hosts: "elastic-cluster-elasticsearch-client:9200"
  pipeline: benchmark-only
  challenge: append-no-conflicts
  persistence:
    size: 50Gi
    storageClass: high
  config:
    nodes: 3