apiVersion: perf.kubestone.xridge.io/v1alpha1
kind: YcsbBench
metadata:
  name: ycsbbench-sample
spec:
  image:
    name: diamantisolutions/ycsb:latest
  action: load
  db_type: redis
  workletter: a
  db_args: -p redis.host=10.0.0.1
