apiVersion: perf.kubestone.xridge.io/v1alpha1
kind: Sysbench
metadata:
  name: sysbench-sample
spec:
  image:
    name: xridge/sysbench:latest
    # pullPolicy: IfNotPresent
    # pullSecret: null
  options: --threads=1 --time=10
  testName: cpu
  command: run
