
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: iperf3s.perf.kubestone.xridge.io
spec:
  group: perf.kubestone.xridge.io
  names:
    kind: Iperf3
    plural: iperf3s
  scope: ""
  validation:
    openAPIV3Schema:
      description: Iperf3 is the Schema for the iperf3s API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Iperf3Spec defines the Iperf3 Benchmark Job
          properties:
            time:
              description: time in seconds to transmit for
              format: int32
              type: integer
            udp:
              description: Use UDP rather than TCP
              type: boolean
          type: object
        status:
          description: Iperf3Status defines the observed state of Iperf3
          properties:
            completed:
              description: Shows completion of benchmark
              type: boolean
            running:
              description: Shows if the benchmark is running
              type: boolean
          required:
          - completed
          - running
          type: object
      type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
